version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: hhplus-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=application
      - MYSQL_PASSWORD=application
      - MYSQL_DATABASE=hhplus
    volumes:
      - ./data/mysql/:/var/lib/mysql
      - ./mysql-config/my.cnf:/etc/mysql/conf.d/my.cnf
    command: 
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-authentication-plugin=mysql_native_password
      - --bind-address=0.0.0.0
      - --max-connections=500
      - --innodb-buffer-pool-size=256M
      - --innodb-log-file-size=64M
      - --innodb-flush-log-at-trx-commit=2
      - --innodb-buffer-pool-instances=4
      - --innodb-io-capacity=2000
    networks:
      - hhplus-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      timeout: 5s
      retries: 10
      start_period: 30s
      interval: 10s

  redis:
    image: redis:7-alpine
    container_name: hhplus-redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis/:/data
      - ./redis-config/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - hhplus-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 3s
      retries: 5
      start_period: 10s
      interval: 5s

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: hhplus-redis-commander
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - hhplus-network

  # Kafka 서비스 (KRaft 모드)
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: hhplus-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://kafka:29093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: 4L6g3nShT-eMCtK--X86sw  # KRaft 모드용 고정 클러스터 ID
    volumes:
      - ./data/kafka:/tmp/kraft-combined-logs
    networks:
      - hhplus-network
    command: >
      bash -c "
        # KRaft 모드 초기 설정
        kafka-storage format --config /etc/kafka/kafka.properties --cluster-id 4L6g3nShT-eMCtK--X86sw || true
        # Kafka 서버 시작
        /etc/confluent/docker/run
      "
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list"]
      timeout: 10s
      retries: 10
      start_period: 45s
      interval: 10s

networks:
  hhplus-network:
    driver: bridge