spring:
  application:
    name: hhplus
  profiles:
    active: test

# SpringDoc/Swagger 설정
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /api-docs
    display-request-duration: true
    display-operation-id: false
    tags-sorter: alpha
    operations-sorter: alpha
  show-actuator: false


---
# JPA + MySQL 환경 (일반적인 모든 환경)
spring.config.activate.on-profile: local, dev, prod

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hhplus?characterEncoding=UTF-8&serverTimezone=UTC
    username: application
    password: application
    driver-class-name: com.mysql.cj.jdbc.Driver
  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        use_sql_comments: true
  # Retry 설정 (동시성 제어용)
  retry:
    enabled: true
  # Redis 설정 (분산 락)
  data:
    redis:
      host: localhost
      port: 6379
      password: 
      timeout: 2000

---
# TestContainers 환경 (통합 테스트용)
spring.config.activate.on-profile: integration-test

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  retry:
    enabled: false  # 통합 테스트에서는 재시도 비활성화

---
# 테스트 환경 (TestContainers 사용)
spring.config.activate.on-profile: test

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  retry:
    enabled: false  # 테스트에서는 재시도 비활성화

