spring:
  application:
    name: hhplus
  profiles:
    active: dev
  datasource:
    name: HangHaePlusDataSource
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 3
      connection-timeout: 10000
      max-lifetime: 60000
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.timezone.default_storage: NORMALIZE_UTC
      hibernate.jdbc.time_zone: UTC
      hibernate:
        format_sql: true

# SpringDoc/Swagger 설정
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /api-docs
    display-request-duration: true
    display-operation-id: false
    tags-sorter: alpha
    operations-sorter: alpha
  show-actuator: false

# Retry 설정 (동시성 제어용)
  retry:
    # 전역 재시도 활성화
    enabled: true

---
# JPA + MySQL 환경 (일반적인 모든 환경)
spring.config.activate.on-profile: local, test, dev, prod

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hhplus?characterEncoding=UTF-8&serverTimezone=UTC
    username: application
    password: application
    driver-class-name: com.mysql.cj.jdbc.Driver
  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        use_sql_comments: true

---
# TestContainers 환경 (통합 테스트용)
spring.config.activate.on-profile: integration-test

spring:
  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        use_sql_comments: true

---
spring.config.activate.on-profile: test_inmemory

spring:
  # ===== H2 인메모리 데이터베이스 (InMemory Repository 전용) =====
  # H2 Console: http://localhost:8080/h2-console
  datasource:
    url: jdbc:h2:mem:hhplus;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true  # H2 웹 콘솔 활성화
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop  # 시작시 테이블 생성, 종료시 삭제
    show-sql: true  # SQL 쿼리 로그 출력
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true  # SQL 포맷팅
